### ISSUE TITLE
html skeleton

### ISSUE THREAD

**Issue by Rufasa85** [Rufasa85/manatee-joke-buttons#2]
## User Story 
GIVEN I visit the site
THEN there should be a page
SO THAT I can see the jokes

## Tasks
- [x] `index.html` exists
- [x] `style.css` exists and is linked
- [x] `script.js` exists and is linked
- [x] `h1` that says `Manatee Jokes!` exists
- [x] contains a `div` holding all the content except the h1
- [x] `h2` with id of `setup`
- [x] `h2` with id of `punchline`
- [x] `button` to show punchline/ get new joke
