### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by Rufasa85** [Rufasa85/manatee-joke-buttons#4]
## User Story
AS A fan of nice looking sites
I WANT some modern styling
SO THAT the page is aestheically pleasing

## Tasks
 - [x] Color div 
 - [x] round div edges
 - [x] center text
 - [x] made button bigger
 - [x] gave button background
